language: python
python:
    - "3.5"
env:
    - TOXENV=django18
    - TOXENV=coverage
install:
    - pip install tox
before_script:
  - psql -c 'create database tablo_test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d tablo_test
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d tablo_test
  # - psql -f test_data.sql -U postgres -d tablo_test
script:
    - tox