language: python
python:
  - "3.5"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
env:
  - TOXENV=django18
  - TOXENV=django19
  - TOXENV=django110
  - TOXENV=django111
  - TOXENV=coverage

sudo: true  # Allow the sudo command

install:
  - pip install tox
  - sudo service postgresql restart
before_script:
  - psql -c 'create database tablo;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d tablo
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d tablo
script:
  - tox