# Generated by Django 5.2.13 on 2026-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tablo", "0007_update_integer_columns_to_bigint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryfile",
            name="file",
            field=models.FileField(max_length=1024, upload_to="storage/tablo/temp/"),
        ),
        migrations.AlterField(
            model_name="temporaryfile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
