# Generated by Django 5.2.13 on 2026-07-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tablo", "0008_alter_temporaryfile_file_alter_temporaryfile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureservicelayer",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layers",
                to="tablo.featureservice",
            ),
        ),
        migrations.AlterField(
            model_name="temporaryfile",
            name="file",
            field=models.FileField(max_length=1024, upload_to="temp"),
        ),
    ]
